[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["net", "macros", "rt-multi-thread"] }
axum = "0.7.4"
axum-oidc = { path = "./../.." }
tower = "0.4.13"
tower-sessions = "0.11.0"

dotenvy = "0.15.7"

[dev-dependencies]
testcontainers = "0.15.0"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
env_logger = "0.11.3"
log = "0.4.21"
headless_chrome = "1.0.9"
