name: Cargo Build & Test

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 1,7,14,21 * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: axum-oidc - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable
        - nightly
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: cargo build --verbose --release
    - run: cargo test --verbose --release

  build_and_test_examples:
    name: axum-oidc - examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install chromium-browser -y
    - run: rustup update stable && rustup default stable
    - run: cargo build --verbose --release
      working-directory: ./examples/basic
    - run: cargo test --verbose --release
      working-directory: ./examples/basic
